experiment:
  dataset: hgd         # [hgd, bciciv2a]
  subject_id: 1
  type: ccsa_da               # [no_tl, loo_tl, ccsa_da]
  n_folds: 4
  i_valid_fold: 0           # [0, 1, 2, 3]

model:
  name: deep           # [eegnet, deep, shallow]
  i_feature_alignment_layer: null  # index of conv layer to apply feature space alignment (0-based)

train:
  early_stop_patience: 80  # 80 hgd, 160 bciciv2a
  max_epochs: 800  # 800 hgd, 1600 bciciv2a
  batch_size: 60

optimizer:
  lr: 0.001
  weight_decay: 0

cropped:
  use: False
  input_time_length: 1000
  final_conv_length_shallow: 30
  final_conv_length_deep: 2

data:
  hgd:
    proc_path: data/hgd_processed_low_cut_4hz
    n_classes: 4
    n_subjects: 14
  bciciv2a:
    proc_path: data/bciciv2a_processed_low_cut_4hz
    n_classes: 4
    n_subjects: 9

server:
  full_cv: True  # True = train all subjects on all valid folds
